### ISSUE TITLE
[USER-v2] Add QoL Features for Managing Multiple Payments in Dashboard V2

### ISSUE THREAD

**Issue by vmichalik** [superfluid-org/superfluid-dashboard#210]
SDK Changes Required for Batching Transactions

- [ ] [SDK-REDUX] Add batch support
- [ ] [SDK-REDUX] Separate transaction execution from preparation

Dashboard Functionality

- [ ] [USER-v2] Batch cancellation of streams (Mostly ready with design)
- [ ] [USER-v2] Batch starting of streams (Needs design)

- [ ] Accounting export functionality (Needs further specification)
