### ISSUE TITLE
[USER-v2] Add closed-ended for Streams to Dashboard V2

### ISSUE THREAD

**Issue by vmichalik** [superfluid-org/superfluid-dashboard#211]
Assumptions:
- Superfluid will initially pay the full cost of automations integrated into the Dashboard V2
- Initially this feature will only be made available on Polygon

- [x] [SPIKE] Review web3 action frameworks for suitability

Specified end-date streams added
- [x] Design
- [x] Price modelling for running the service (on Polygon)
- [x] [USER-v2] Add support for the auto-close contract (may need SDK changes)
- [ ] [USER-v2] Make the feature available on Goerli testnet
- [ ] [USER-v2] Make the feature available on Polygon mainnet

Future work
- [ ] Price modelling for running the service (on other L2s)
- [ ] [USER-v2] Make the feature available on L2 testnets
- [ ] Determine a sustainable funding model for these automations
